---
title: "poisson_modified"
author: "Gulzina Kuttubekova"
date: "5/13/2020"
output: pdf_document
---

```{r}
library(ggplot2)
library(ggpubr)
library(dplyr)
library(reshape)
library(LearnBayes)
library(rmutil)
```

Read the dataset:
```{r}
covid <- read.csv("~/Desktop/spring2020/stat207/bayesian-analysis-of-COVID19-in-CA/data/Covid19-04-13-20.txt")

covid$Population <- covid$Population/1000
```


Use Gibbs sampling to sample from joint posterior distribution of theta, and lambda.  

```{r}
# use the same samples you got from the previous study
rej_ss %>% apply(2, mean)
```

```{r}
# for ith county
log_lik <- function(lambda, mu, tau, theta, c, n, y) {
    res <- theta^(mu*tau + n + y - 1)
    res <- res*(1-theta)^((1-mu)*tau - 1 + n - y) * exp(-theta*lambda*c)

    return(res)
}
```


```{r}
full_theta_mh <- function(lambda, mu, tau, theta, C, N, y) {
    thetas <- c()
    var_tuning = 0.01
    
    for (i in 1:58) {
        prop <- rnorm(1, log(theta[i]), sqrt(var_tuning))
        acceptance_prob <- min(
            exp(log_lik(lambda, mu, tau, exp(prop), C[i], N[i], y[i])-log_lik(lambda, mu, tau, theta[i], C[i], N[i], y[i])), 1)
        u <- runif(1)
        
        if (!is.nan(acceptance_prob) & (u < acceptance_prob)) {
            thetas[i] <- exp(prop)
        } else {
            thetas[i] <- theta[i]
        }
    }
    
    return(thetas)
}
```


```{r}
# Write Gibbs sampling 
gibbs <- function(a, b, lambda_init, thetas_init, mu, tau, C, N, y) {
    # constants
    niter = length(mu)
    sum_n = sum(N)
    lambda_temp = lambda_init
    thetas_temp = thetas_init
    
    # results
    thetas = c()
    lambda <- c()
    
    for (i in 1:niter) {
        # sample thetas using MH
        thetas_temp = full_theta_mh(lambda_temp, mu[i], tau[i], 
                                    thetas_temp, C, N, y)
        thetas = rbind(thetas, thetas_temp)
        
        # sample lambda
        lambda_temp = rgamma(1, shape = n + a, 
                            scale = 1/(1/b + sum(thetas_temp*C)))
        lambda[i] <- lambda_temp
    }
    
    return(list(thetas, lambda))
}
```


```{r}
theta_init <- rep(0.05, 58)
lambda_init <- 20

samples <- gibbs(20, 10, lambda_init, theta_init, 
                 rej_ss$mu, rej_ss$tau, 
                 covid$Population, covid$Total.cases, 
                 covid$Deaths)
```

```{r}
theta <- theta_init
lambda <- lambda_init
mu <- rej_ss$mu
tau <- rej_ss$tau
N <- covid$Total.cases
C <- covid$Population
y <- covid$Deaths
```

```{r}
thetas2 <- samples[[1]]
lambdas2 <- samples[[2]]
```

```{r}
thetas2 %>% apply(2, mean)
```

```{r}
lambdas2 %>% mean()
lambdas2 %>% quantile(probs = c(0.025, 0.5, 0.975))
```

```{r}
# posterior and prior lambda
sl <- data.frame(posterior = lambdas2, 
                 prior = rgamma(length(lambdas2), 20, scale = 10))
sl_melt <- melt(sl, measure.vars = c('posterior', 'prior'))
colnames(sl_melt) <- c('type', 'lambda')
```

```{r}
ggdensity(sl_melt, 'lambda', fill = 'type') + 
    ylab("") +
    xlim(0, 2000)
```



Compare the mortality rate for each county:
```{r}
# rename columns
colnames(thetas2) <- covid$County

# melt
thetas2_melt <- melt(thetas2)

# boxplots
thetas2_melt %>% ggplot(aes(y=value, x=X2)) + 
    geom_boxplot(outlier.size = 0.5) + 
    theme(axis.text.x = element_text(angle = 90, size = 6)) + 
    ggtitle('Distribution of lambda by county') +
    xlab("") + 
    ylab("lambda")
```

```{r}
covid$post_death_rate <- apply(thetas, 2, mean)
```

```{r}
# ggplot using three variables
covid %>% filter(post_death_rate != 0) %>% 
    ggplot(aes(x=County, y=post_death_rate)) + 
    geom_bar(stat = "identity") + coord_flip() +
    theme(axis.text.y = element_text(size = 6)) + 
    ggtitle('Posterior distribution of death rate by county') +
    ylim(0.0, 0.1)
```

```{r}
mean(covid$post_death_rate) * sum(covid$Total.cases)
```


Now generate posterior predictive ns:
```{r}
#' Draw one sample from predictive distribution of n for all counties
#' 
#' @param lambda one sample of lambda
#' @param theta one sample of theta's
#' @param C population of 58 counties
#' @return 1*58-dim vector with samples of n for all counties
predictive_n<- function(lambda, C, theta) {
    s <- c()
    
    for (i in 1:58) {
        s[i] <- rpois(1, lambda = lambda*theta[i]*C[i])
    }
    
    return(s)
}
```

```{r}
# sample n's
n <- length(lambdas2)
ns2 <- c()
for (i in 1:n) {
    temp <- predictive_n(lambdas2[i], covid$Population, thetas2[i,])
    ns2 <- rbind(ns2, temp)
} 
```

```{r}
#' Draw one sample from predictive distribution of y for all counties
#' 
#' @param n one sample of n
#' @param theta one sample of theta's
#' @return 1*58-dim vector with samples of n for all counties
predictive_y<- function(n, theta) {
    s <- c()
    
    for (i in 1:58) {
        s[i] <- rbinom(1, size = n[i], prob = theta[i])
    }
    
    return(s)
}
```

```{r}
# sample y's
ys <- c()
for (i in 1:n) {
    temp <- predictive_y(ns2[i,], thetas2[i,])
    ys <- rbind(ys, temp)
}
```

```{r}
dss <- matrix(NA, nrow = nrow(ys), ncol = ncol(ys))

# multiply each mean theta by n_i's
for (i in 1:58) {
    dss[,i] <- ys[,i] / covid$Population[i] 
}
```


```{r}
# rename columns
colnames(dss) <- covid$County

# melt
dss_melt <- melt(dss)

# boxplots
dss_boxplots <- dss_melt %>%  
    ggplot(aes(y=value, x=X2)) + 
    geom_boxplot(outlier.size = 0) + 
    theme(axis.text.x = element_text(angle = 90, size = 6)) + 
    ggtitle('Distribution of number of deaths per 1000 habitants') +
    xlab("") + 
    ylab("deaths per 1000")
```

```{r}
dss_boxplots
```

Top five counties:
```{r}
dss %>% apply(2, mean) %>% sort()
```


Calculate share posterior probs:
```{r}
n <- nrow(ns2)
probs_left <- c()
probs_right <- c()
count <- 1

for (j in c(1, 2, 5, 7, 10, 15, 18, 24, 26)) {
    # percentage captured by Orange only
    real <- covid$Total.cases[j] / sum(covid$Total.cases)

    # sampled
    share <- c()
    for (i in 1:n) {
        share[i] <- ns2[i,j] / sum(ns2[i,])
    }
    
    probs_left[count] <- sum(real < share) / n
    probs_right[count] <- sum(real > share) / n
    
    count <- count + 1
    # plot
    #share %>% hist(ylab = "", xlab = 'T(n)',main = covid$County[j])
    #abline(v=real, col="red")
}
```

```{r}
cbind(probs_left, probs_right)
```

Predictive n comparison
```{r}
nss <- matrix(NA, nrow = nrow(ns2), ncol = ncol(ns2))

# multiply each mean theta by n_i's
for (i in 1:58) {
    nss[,i] <- ns2[,i] / covid$Population[i] 
}
```

```{r}
covid$nss_means <- apply(nss, 2, mean)
```

```{r}
covid %>% filter(nss_means != 0) %>% 
    ggplot(aes(x=County, y=nss_means)) + 
    geom_bar(stat = "identity") + coord_flip() +
    ylab("infection per 1000") +
    theme(axis.text.y = element_text(size = 6)) + 
    ggtitle('Posterior predictive distribution of infection by county')
    
```


```{r}
# rename columns
colnames(nss) <- covid$County

# melt
nss_melt <- melt(nss)

# boxplots
nss_boxplots <- nss_melt %>%  
    ggplot(aes(y=value, x=X2)) + 
    geom_boxplot(outlier.size = 0) + 
    theme(axis.text.x = element_text(angle = 90, size = 6)) + 
    ggtitle('Distribution of number of deaths per 1000 habitants') +
    xlab("") + 
    ylab("deaths per 1000")
```

```{r}
nss_boxplots
```




















